archival:
  history:
    status: "disabled"
    enableRead: false
  visibility:
    status: "disabled"
    enableRead: false

domainDefaults:
  archival:
    history:
      status: "disabled"
      URI: ""
    visibility:
      status: "disabled"
      URI: ""

persistence:
  advancedVisibilityStore: es-visibility
  datastores:
    es-visibility:
      elasticsearch:
        version: "v7"
        url:
          scheme: "http"
          host: "127.0.0.1:9200"
        indices:
          visibility: cadence-visibility-dev

kafka:
  tls:
    enabled: false
  clusters:
    test:
      brokers:
        - 127.0.0.1:9092
  topics:
    cadence-visibility-dev:
      cluster: test
    cadence-visibility-dev-dlq:
      cluster: test
  applications:
    visibility:
      topic: cadence-visibility-dev
      dlq-topic: cadence-visibility-dev-dlq

dynamicconfig:
  client: filebased
  filebased:
    filepath: "config/dynamicconfig/development_es.yaml"

blobstore:
  filestore:
    outputDirectory: "/tmp/blobstore"

authorization:
  oauthAuthorizer:
    enable: true
    maxJwtTTL: 600000000
    jwtCredentials:
      algorithm: "RS256"
      publicKey: "config/credentials/keytest.pub"